version: "3"

services:
  firefox:
    image: jlesage/firefox:v1.17.1
    container_name: firefox
    shm_size: 2gb
    ports:
      - 5800:5800
    volumes:
      - ./firefox/user.js:/config/profile/user.js
    depends_on:
      - node

  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    container_name: ganache

  node:
    build:
      context: .
    container_name: node
    volumes:
      - ./apps:/apps
    depends_on:
      - ganache
